FROM node:24-alpine AS builder
WORKDIR /app

# Native build tools required by some npm packages
RUN apk add --no-cache python3 make g++

# Install the exact pnpm version used by the project
RUN corepack enable && corepack prepare pnpm@10.33.0 --activate

# Copy workspace manifests before source for better layer caching
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml .npmrc ./
COPY lib/db/package.json lib/db/
COPY lib/api-zod/package.json lib/api-zod/
COPY lib/api-spec/package.json lib/api-spec/
COPY lib/api-client-react/package.json lib/api-client-react/
COPY artifacts/api-server/package.json artifacts/api-server/
COPY artifacts/mobile/package.json artifacts/mobile/
COPY artifacts/mockup-sandbox/package.json artifacts/mockup-sandbox/
COPY scripts/package.json scripts/

# Install all dependencies — no frozen-lockfile since Railway's pnpm version
# conflicts with the lockfile generated by pnpm v10
RUN pnpm install --no-frozen-lockfile

# Copy remaining source files
COPY . .

# Build the api-server bundle
RUN pnpm --filter @workspace/api-server run build

# Create a self-contained production directory (production deps only)
RUN pnpm deploy --filter @workspace/api-server --prod --legacy /prod


FROM node:24-alpine
WORKDIR /app

# Production node_modules from pnpm deploy
COPY --from=builder /prod/node_modules ./node_modules

# Built bundle — copied separately because dist/ is gitignored
# and pnpm deploy won't include it
COPY --from=builder /app/artifacts/api-server/dist ./dist

ENV NODE_ENV=production

CMD ["node", "--enable-source-maps", "./dist/index.mjs"]
