import { Feather } from "@expo/vector-icons";
import * as Haptics from "expo-haptics";
import { router } from "expo-router";
import React, { useRef, useState } from "react";
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import Colors from "@/constants/colors";
import { useAuth } from "@/context/AuthContext";

const BASE_URL = `https://${process.env.EXPO_PUBLIC_DOMAIN}`;

export default function PairScreen() {
  const insets = useSafeAreaInsets();
  const { loginRestaurant } = useAuth();
  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handlePair = async () => {
    const trimmed = code.trim().toUpperCase();
    if (trimmed.length < 6 || loading) return;
    setLoading(true);
    setError("");

    try {
      const response = await fetch(`${BASE_URL}/api/auth/device/pair`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code: trimmed }),
      });

      if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        const msg =
          response.status === 410
            ? "This code has expired. Ask your admin for a new one."
            : response.status === 409
            ? "This code has already been used."
            : response.status === 404
            ? "Invalid pairing code. Please check and try again."
            : (err as { error?: string }).error ?? "Pairing failed. Please try again.";
        setError(msg);
        await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
        return;
      }

      const data = await response.json() as { token: string; restaurant: { id: number; name: string; location: string; createdAt: string } };
      await loginRestaurant(data.token, data.restaurant);
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      router.replace("/(restaurant)");
    } catch {
      setError("Connection failed. Please check your network.");
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <KeyboardAvoidingView
      style={[styles.container, { paddingTop: insets.top + (Platform.OS === "web" ? 67 : 0) }]}
      behavior={Platform.OS === "ios" ? "padding" : "height"}
    >
      <View style={styles.inner}>
        <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
          <Feather name="arrow-left" size={20} color={Colors.primary} />
          <Text style={styles.backText}>Back</Text>
        </TouchableOpacity>

        <View style={styles.iconContainer}>
          <Feather name="link" size={36} color={Colors.primary} />
        </View>

        <Text style={styles.title}>Pair Restaurant Device</Text>
        <Text style={styles.subtitle}>
          Enter the 6-character pairing code generated by your admin. Codes expire after 15 minutes.
        </Text>

        <View style={styles.codeInputContainer}>
          <TextInput
            style={styles.codeInput}
            value={code}
            onChangeText={(v) => { setCode(v.toUpperCase()); setError(""); }}
            placeholder="ABC123"
            placeholderTextColor={Colors.textTertiary}
            autoCapitalize="characters"
            autoCorrect={false}
            maxLength={6}
            returnKeyType="done"
            onSubmitEditing={handlePair}
            autoFocus
          />
        </View>

        {error ? (
          <View style={styles.errorContainer}>
            <Feather name="alert-circle" size={16} color={Colors.accent} />
            <Text style={styles.errorText}>{error}</Text>
          </View>
        ) : null}

        <TouchableOpacity
          style={[styles.pairBtn, (loading || code.trim().length < 6) && styles.pairBtnDisabled]}
          onPress={handlePair}
          disabled={loading || code.trim().length < 6}
          activeOpacity={0.8}
        >
          {loading ? (
            <ActivityIndicator color="#FFFFFF" />
          ) : (
            <>
              <Feather name="link" size={18} color="#FFFFFF" />
              <Text style={styles.pairBtnText}>Pair Device</Text>
            </>
          )}
        </TouchableOpacity>

        <Text style={styles.hint}>
          Once paired, this device will stay connected to its restaurant until an admin revokes access.
        </Text>
      </View>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  inner: {
    flex: 1,
    padding: 28,
    paddingTop: 20,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    marginBottom: 36,
  },
  backText: {
    fontSize: 16,
    color: Colors.primary,
    fontFamily: "Inter_500Medium",
  },
  iconContainer: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: Colors.primaryLight + "22",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    alignSelf: "center",
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: Colors.text,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 15,
    color: Colors.textSecondary,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 36,
  },
  codeInputContainer: {
    marginBottom: 16,
  },
  codeInput: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: Colors.border,
    paddingHorizontal: 24,
    paddingVertical: 20,
    fontSize: 32,
    fontWeight: "700",
    fontFamily: "Inter_700Bold",
    color: Colors.primary,
    textAlign: "center",
    letterSpacing: 8,
  },
  errorContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: Colors.accent + "15",
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
  },
  errorText: {
    color: Colors.accent,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    flex: 1,
  },
  pairBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 18,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
    marginBottom: 20,
  },
  pairBtnDisabled: {
    opacity: 0.5,
  },
  pairBtnText: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "600",
    fontFamily: "Inter_600SemiBold",
  },
  hint: {
    fontSize: 13,
    color: Colors.textTertiary,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 18,
  },
});
